services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=escolar
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: